Add application info to the executable.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,7 +37,17 @@ jobs:
           VERSION_ARRAY=$(echo "$VERSION_NUM" | tr '.' ',' | sed 's/\(.*\)/[\1]/')
           
           PAGES_URL_ROOT="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
-          DOWNLOAD_FILE="pyrepl_${VERSION}-win.zip" 
+          DOWNLOAD_FILE="pyrepl_${VERSION}-win.zip"
+
+          # Define executable directory
+          EXE_NAME="pyrepl_${VERSION}.exe"
+          EXE_PATH="HeyheyEason PyREPL/dist/windows/$EXE_NAME"
+          
+          # Check executable existence
+          if [ ! -f "$EXE_PATH" ]; then
+            echo "::error file=$EXE_PATH::Assigned executable not found. Please make sure that $EXE_PATH exists in master branch."
+            exit 1
+          fi
           
           # Create version.json (use VERSION_ARRAY variable)
           echo "{\"latest_version\": $VERSION_ARRAY, \"download_url\": \"${PAGES_URL_ROOT}${DOWNLOAD_FILE}\", \"notes\": \"Windows Installer Pack\"}" > pages_assets/version.json
@@ -48,7 +58,7 @@ jobs:
           # 3. Create pyrepl_vx.y.z.zip
           zip -r pages_assets/${DOWNLOAD_FILE} \
             "HeyheyEason PyREPL/data" \
-            "HeyheyEason PyREPL/dist/windows"
+            "$EXE_PATH"
           
       # 4. Set and activate Pages 
       - name: Set and activate GitHub Pages
